version: "3.8"

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker:ro
    environment:
      - JENKINS_OPTS=--httpPort=8080
    restart: unless-stopped
    user: root

  jenkins-agent:
    image: jenkins/inbound-agent:latest
    container_name: jenkins-agent
    environment:
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_SECRET=your-agent-secret 
      - JENKINS_AGENT_NAME=docker-agent
    depends_on:
      - jenkins
    restart: unless-stopped

volumes:
  jenkins_home:
