deploy_staging:
  stage: deploy
  before_script:
    - npm install -g firebase-tools
  script:
    - firebase deploy --only hosting:staging --token $FIREBASE_TOKEN
  only:
    - develop

deploy_production:
  stage: deploy
  before_script:
    - npm install -g firebase-tools
  script:
    - firebase deploy --only hosting:production --token $FIREBASE_TOKEN
  only:
    - main
