services:
  app:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile  # Adjust the path to the Dockerfile location

    volumes:
      - ..:/usr/src/app  # Ensure correct path
    ports:
      - "3000:3000"
    command: bash -c "npm install && npm start"
