version: "3.8"

services:
  angular-app-prod:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - angular-app-prod
    restart: unless-stopped
